[package]
name = "cyberjohn8/directorio"
version = "1.0.0"
description = "Mi directorio web"
license = "MIT"

[[static]]
path = "/"
location = "."

[command]
name = "web"
module = "static-web-server"
runner = "wasmer/static-web-server"